[supervisord]
nodaemon=true
user=root

[program:anvil]
command=anvil --fork-url https://mainnet.base.org --chain-id 8453 --port 8545 --block-time 2
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:bot]
command=/usr/local/bin/mevbot
autostart=true
autorestart=true
environment=BASE_HTTP_RPC="http://localhost:8545",BASE_WS_RPC="http://localhost:8545",BASE_EXEC_RPC="http://localhost:8545",ANVIL_RPC="http://localhost:8545",PRIVATE_KEY="ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",FLASH_EXECUTOR_ADDRESS="0x3F578E32b34E0c694f1d817CFb53b89e5C2D1847",MIN_PROFIT_USD="0.01",LOAN_PROVIDER="BALANCER"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:chaos]
command=/bin/bash /usr/local/bin/chaos.sh
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
